100-hours-a-week/11-ellu-be

- .github/workflows/semantic-release.yml
- resolve #7
- chore: semantic-release 적용
- chore: spotless 커밋 규칙 수정
> Chore 7 maintenance semantic release 적용

- src/main/java/com/ellu/looper/commons/enums/Color.java
- src/main/java/com/ellu/looper/commons/enums/Role.java
- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/controller/AuthController.java
- src/main/java/com/ellu/looper/controller/ProjectController.java
- src/main/java/com/ellu/looper/dto/LoginResponse.java
- src/main/java/com/ellu/looper/dto/MemberDto.java
- src/main/java/com/ellu/looper/dto/ProjectCreateRequest.java
- src/main/java/com/ellu/looper/dto/ProjectListResponse.java
- src/main/java/com/ellu/looper/dto/ProjectMemberResponse.java
- src/main/java/com/ellu/looper/dto/ProjectResponse.java
- src/main/java/com/ellu/looper/dto/WikiRequest.java
- src/main/java/com/ellu/looper/entity/Project.java
- src/main/java/com/ellu/looper/entity/ProjectMember.java
- src/main/java/com/ellu/looper/exception/GlobalExceptionHandler.java
- src/main/java/com/ellu/looper/jwt/JwtAuthenticationFilter.java
- src/main/java/com/ellu/looper/jwt/JwtAuthenticationToken.java
- src/main/java/com/ellu/looper/jwt/JwtExpiration.java
- src/main/java/com/ellu/looper/repository/ProjectMemberRepository.java
- src/main/java/com/ellu/looper/repository/ProjectRepository.java
- src/main/java/com/ellu/looper/repository/UserRepository.java
- src/main/java/com/ellu/looper/service/AiService.java
- src/main/java/com/ellu/looper/service/AuthService.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- src/main/java/com/ellu/looper/service/UserService.java
- resolve #
- 개요 작성
Project domain api 작성
refresh token cookie 설정
> feat: Jwt 쿠키 설정 및 Project Domain API 구현(#10)

- src/main/java/com/ellu/looper/controller/AuthController.java
- src/main/java/com/ellu/looper/dto/AuthResponse.java
- src/main/resources/application.properties
- resolve #12 
- 개요 작성
- 로그인 시 응답 형식을 API 명세서에 맞게 수정했습니다.
- db port를 변경했습니다.
- 선택사항 입니다.
> fix: 로그인 시 응답 형식 수정(#12)

- src/main/java/com/ellu/looper/controller/AuthController.java
- src/main/java/com/ellu/looper/controller/MeetingNoteController.java
- src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
- src/main/java/com/ellu/looper/controller/ScheduleController.java
- src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
- src/main/java/com/ellu/looper/dto/ProjectCreateRequest.java
- src/main/java/com/ellu/looper/dto/UserResponse.java
- src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleResponse.java
- src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleUpdateRequest.java
- src/main/java/com/ellu/looper/dto/schedule/ScheduleCreateRequest.java
- src/main/java/com/ellu/looper/dto/schedule/ScheduleResponse.java
- src/main/java/com/ellu/looper/dto/schedule/ScheduleUpdateRequest.java
- src/main/java/com/ellu/looper/exception/GlobalExceptionHandler.java
- src/main/java/com/ellu/looper/exception/ValidationException.java
- src/main/java/com/ellu/looper/repository/ProjectScheduleRepository.java
- src/main/java/com/ellu/looper/service/AuthService.java
- src/main/java/com/ellu/looper/service/FastApiService.java
- src/main/java/com/ellu/looper/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- src/main/java/com/ellu/looper/service/ScheduleService.java
- src/main/java/com/ellu/looper/service/UserService.java
- resolve #25 
- API 응답형식에 맞게 수정(minor changes)
> fix: API 응답 형식에 맞게 수정(#25)

- .env.template 
- .gitignore
- build.gradle
- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/config/SwaggerConfig.java
- src/main/resources/application.yml
- resolve #29
- feat: Swagger 설정
- d4624260f733cffdd0ae5a21d700725ef4fec825
- 선택사항 입니다.
> feat: Swagger 설정 (#29)

- src/main/java/com/ellu/looper/config/SecurityConfig.java
- resolve #
- 개요 작성
- 선택사항 입니다.
> feat: looper.my 도메인 CORS 허용 설정 추가

- src/main/java/com/ellu/looper/dto/LoginResponse.java
- resolve #
- 개요 작성
- 선택사항 입니다.
> fix: is_new_user 변수명 수정

- src/main/java/com/ellu/looper/dto/AuthResponse.java
- src/main/resources/application.yml
- resolve #37 
- 개요 작성
- 선택사항 입니다.
> fix: is_new_user 변수명 수정 (#37)

- src/main/resources/application.yml
- resolve #
- 개요 작성
- 선택사항 입니다.
> hotfix: swagger 변수 application.yml에 추가

- src/main/java/com/ellu/looper/config/SwaggerConfig.java
- resolve #
- 개요 작성
- 선택사항 입니다.
> hotfix: swaggerURL 변경

- src/main/java/com/ellu/external/FastApiClient.java
- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/config/WebClientConfig.java
- src/main/java/com/ellu/looper/controller/AuthController.java
- src/main/java/com/ellu/looper/controller/ProfileImageController.java
- src/main/java/com/ellu/looper/jwt/JwtProvider.java
- src/main/java/com/ellu/looper/service/AuthService.java
- resolve #44
리프레시 토큰 재발급 수정됨
authorization header가 아니라 쿠키로부터 꺼내오도록 수정
> fix: 리프레시 토큰 재발급 수정(#44)

- src/main/java/com/ellu/looper/commons/PreviewHolder.java
- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/controller/FastApiCallbackController.java
- src/main/java/com/ellu/looper/controller/MeetingNoteController.java
- src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
- src/main/java/com/ellu/looper/controller/ScheduleController.java
- src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
- src/main/java/com/ellu/looper/dto/MeetingNoteResponse.java
- src/main/java/com/ellu/looper/dto/MemberDto.java
- src/main/java/com/ellu/looper/dto/WikiRequest.java
- src/main/java/com/ellu/looper/entity/Project.java
- src/main/java/com/ellu/looper/entity/ProjectSchedule.java
- src/main/java/com/ellu/looper/repository/ProjectMemberRepository.java
- src/main/java/com/ellu/looper/service/AuthService.java
- src/main/java/com/ellu/looper/service/FastApiService.java
- src/main/java/com/ellu/looper/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- src/main/java/com/ellu/looper/service/ScheduleService.java
> fix: fastapi, frontend integration(#46)

- src/main/java/com/ellu/looper/service/ProfileImageService.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- src/main/java/com/ellu/looper/service/S3Service.java
- resolve #51 
사용자 프로필 이미지 presigned url적용
> fix: 프로필이미지 파일에 presigned url 적용

- src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
> fix: meeting note dto id field 타입 수정

- src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
Reverts 100-hours-a-week/11-ellu-be#56
> Revert "fix: meeting note dto id field 타입 수정"

- .github/workflows/build.yml
- Dockerfile
- build.gradle
- resolve #
- 개요 작성
- 선택사항 입니다.
> ci: 개발용 컨테이너 이미지 빌드 yml 추가

- src/main/java/com/ellu/looper/controller/AuthController.java
- src/main/java/com/ellu/looper/jwt/JwtAuthenticationFilter.java
- src/main/java/com/ellu/looper/service/AuthService.java
- src/main/resources/application.yml
> hotfix: async 처리

- src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleResponse.java
- src/main/java/com/ellu/looper/dto/schedule/ScheduleResponse.java
- src/main/java/com/ellu/looper/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- src/main/java/com/ellu/looper/service/ScheduleService.java
- resolve #71 
- 프로젝트 생성/수정 시 색상 입력 처리
- 프로젝트 스케줄 조회 시 프로젝트 색상 정보 조회
- 유저가 속한 스케줄 조회 시 프로젝트 스케줄인 경우 프로젝트 색상 조회
> feat: 프로젝트 색상 필드 처리(#71)

- src/main/java/com/ellu/looper/controller/ProjectController.java
- src/main/java/com/ellu/looper/dto/CreatorExcludedProjectResponse.java
- src/main/java/com/ellu/looper/dto/ProjectUpdateRequest.java
- src/main/java/com/ellu/looper/entity/ProjectMember.java
- src/main/java/com/ellu/looper/service/ProjectService.java
- resolve #84 
프로젝트 업데이트, 프로젝트 상세 조회 로직 수정
api시트의 응답 형식 변경요청에 따른 dto추가
> feat: project detail view dto & project update logic revised

- src/main/java/com/ellu/looper/kafka/NotificationConsumer.java
- src/main/java/com/ellu/looper/kafka/NotificationProducer.java
- src/main/resources/application.yml
> maintenance: kafka 환경 변수 설정

- src/main/java/com/ellu/looper/LooperApplication.java
- src/main/resources/application.yml
> fix: timezone 설정

- src/main/resources/application.yml
- resolve #
- 개요 작성
- 선택사항 입니다.
> fix: kafka 환경변수 수정

- src/main/java/com/ellu/looper/fastapi/service/FastApiService.java
- src/main/java/com/ellu/looper/project/controller/MeetingNoteController.java
> fix: webclient complete처리 수정

- src/main/java/com/ellu/looper/chat/controller/ChatController.java
- src/main/java/com/ellu/looper/chat/dto/ChatMessageResponse.java
- src/main/java/com/ellu/looper/chat/entity/ChatConversation.java
- src/main/java/com/ellu/looper/chat/entity/ChatMessage.java
- src/main/java/com/ellu/looper/chat/repository/ChatMessageRepository.java
- src/main/java/com/ellu/looper/chat/service/ChatService.java
- src/main/java/com/ellu/looper/commons/enums/ChatRole.java
- src/main/java/com/ellu/looper/config/StompWebsocketConfig.java
- src/main/java/com/ellu/looper/fastapi/service/FastApiService.java
- src/main/java/com/ellu/looper/jwt/JwtAuthenticationFilter.java
- src/main/java/com/ellu/looper/kafka/PreviewResultConsumer.java
- src/main/java/com/ellu/looper/project/controller/MeetingNoteController.java
- src/main/java/com/ellu/looper/project/service/ProjectService.java
- src/main/java/com/ellu/looper/schedule/controller/ProjectScheduleController.java
- src/main/java/com/ellu/looper/schedule/dto/PlanCreateRequest.java
- src/main/java/com/ellu/looper/schedule/entity/Schedule.java
- src/main/java/com/ellu/looper/schedule/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/schedule/service/ScheduleService.java
- src/main/resources/application.yml
- 채팅 기록 조회 api 추가 
- 개인 캘린더로 가져가기 기능에서 프로젝트 색상 저장되게 수정
> Feat: 채팅 기록 조회 api 추가 및 개인 캘린더로 가져가기 기능에서 프로젝트 색상 저장되게 수정

- src/main/java/com/ellu/looper/commons/util/HangulUtil.java
> fix: 누락된 파일 추가

- .github/workflows/stage.yml
[ci: script에 nginx 재시작 포함](https://github.com/100-hours-a-week/11-ellu-fe/commit/5213e4e6dce77b7f83ba5354bcb569d9d9b052f8)
> ci: script에 nginx 재시작 포함

- build.gradle
- src/main/java/com/ellu/looper/auth/controller/AuthController.java
- src/main/java/com/ellu/looper/auth/dto/KakaoUserResponse.java
- src/main/java/com/ellu/looper/auth/entity/RefreshToken.java
- src/main/java/com/ellu/looper/auth/service/AuthService.java
- src/main/java/com/ellu/looper/auth/service/oauth/KakaoClient.java
- src/main/java/com/ellu/looper/chat/service/ChatService.java
- src/main/java/com/ellu/looper/sse/service/SseEmitterService.java
- src/main/java/com/ellu/looper/sse/service/SseService.java
- src/main/resources/application.yml
- resolve #156
- 쿠키 없이 refresh 하려는 경우의 예외 처리 추가
- 로그 수정
> fix: 로그 수정 및 예외 처리 추가

- src/main/java/com/ellu/looper/schedule/service/ProjectScheduleService.java
Rewrote commented-out API call for AI schedule recommendation
> feat: 유저의 회의록 선택 결과 전송 

- src/main/java/com/ellu/looper/kafka/config/KafkaStreamsConfig.java
- src/main/java/com/ellu/looper/schedule/dto/PlanCreateRequest.java
- src/main/java/com/ellu/looper/schedule/entity/Plan.java
- src/main/java/com/ellu/looper/schedule/service/ScheduleService.java
- src/main/java/com/ellu/looper/sse/service/SseEmitterService.java
> fix: plan 저장 시 category도 저장하도록 수정

- src/main/java/com/ellu/looper/chat/controller/ChatController.java
- src/main/java/com/ellu/looper/chat/dto/RelatedScheduleRequest.java
- src/main/java/com/ellu/looper/chat/dto/RelatedScheduleResponse.java
- src/main/java/com/ellu/looper/chat/service/ChatService.java
- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/schedule/repository/PlanRepository.java
- src/main/java/com/ellu/looper/schedule/repository/ScheduleRepository.java
- src/main/java/com/ellu/looper/schedule/service/ScheduleService.java
- chatbot 기능 추가
- 관련된 schedule을 query하는 api를 구현함
> Feat: 관련된 개인 스케줄 조회하는 api구현

- src/main/resources/application.yml
- resolve #143
- 추후 부하테스트 시 필요에 따라 브로커 3대로 확장 가능
> refactor: kafka cluster setup

- src/main/java/com/ellu/looper/kafka/ScheduleEventConsumer.java
- src/main/java/com/ellu/looper/project/service/ProjectService.java
- src/main/java/com/ellu/looper/schedule/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/user/repository/UserRepository.java
- src/main/java/com/ellu/looper/user/service/UserService.java
- resolve #198
- 초대가 되지 않은 프로젝트에 있어서 [https://looper.my/projects/ ](https://looper.my/projects/%C2%A0) 뒤의 경로매개변수를 수정하면 해당 프로젝트에 들어갈 수 있음, 해당 프로젝트에 일정 생성 및 수정이 가능함.
- 팀원을 초대할 때 대소문자 구분없이 검색할 수 있도록 수정
> fix: 권한 코드 추가, 닉네임 쿼리 기능 수정

- src/main/java/com/ellu/looper/config/SecurityConfig.java
- src/main/java/com/ellu/looper/exception/GlobalExceptionHandler.java
- src/main/java/com/ellu/looper/kafka/NotificationConsumer.java
- src/main/java/com/ellu/looper/project/controller/ProjectController.java
- src/main/java/com/ellu/looper/sse/service/NotificationSseService.java
> chore: changed extracting subtasks from meeting notes

- src/main/java/com/ellu/looper/kafka/ScheduleEventConsumer.java
- src/main/java/com/ellu/looper/project/service/ProjectService.java
- src/main/java/com/ellu/looper/schedule/service/ProjectScheduleService.java
- src/main/java/com/ellu/looper/user/repository/UserRepository.java
- src/main/java/com/ellu/looper/user/service/UserService.java
> fix: 권한 체크, 닉네임 조회 수정
